
import java.awt.Color;
import java.awt.Frame;  
import java.util.Date; 
import java.text.SimpleDateFormat;
import java.util.Calendar; 
import java.util.GregorianCalendar;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane; 
import java.sql.*; 
import javax.swing.*; 

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADEBAYO ADEMOLA
 */
public class FinalTicket extends javax.swing.JFrame { 

 Connection conn = null; 
 ResultSet rs = null; 
 PreparedStatement pst = null; 
    /**
     * Creates new form FinalTicket
     */ 
 
 

 
    public FinalTicket(String para, String db) { 

        conn = connectSqlite.dbConnector(db);
        initComponents();  
         staff.setText(para); 
         this.setLocationRelativeTo(null);  
         riceLabel.setVisible(false); 
         riceCombo.setEnabled(false); 
         beansLabel.setVisible(false); 
         beansCombo.setEnabled(false); 
         plantainLabel.setVisible(false); 
         plantainCombo.setEnabled(false); 
         saladLabel.setVisible(false); 
         saladCombo.setEnabled(false); 
         eggLabel.setVisible(false); 
         eggCombo.setEnabled(false); 
         meatLabel.setVisible(false); 
         meatCombo.setEnabled(false); 
         fishLabel.setVisible(false); 
         fishCombo.setEnabled(false); 
         pyamLabel.setVisible(false); 
         pyamCombo.setEnabled(false);
         semoLabel.setVisible(false); 
         semoCombo.setEnabled(false); 
         cokeLabel.setVisible(false); 
         cokeCombo.setEnabled(false); 
         fantaLabel.setVisible(false); 
         fantaCombo.setEnabled(false);
         pepsiLabel.setVisible(false); 
         pepsiCombo.setEnabled(false); 
         amalaLabel.setVisible(false); 
         amalaCombo.setEnabled(false);  
         confirmButton.setEnabled(false);
         receiptButton.setEnabled(false); 
         printButton.setEnabled(false); 
          doneButton.setEnabled(false);
         receiptArea.setText( "           WELCOME" + "\n\n" + "    PLEASE CLICK ON THE" + "\n\n\n"  +  "         DONE BUTTON     " + "\n\n\n\n" + "   AFTER MAKING YOUR ORDER  "); 
         
         
        if(riceCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
        else if(beansCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else if(plantainCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else if(pyamCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else if(eggCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else if(saladCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else if(fishCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else if(meatCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else if(cokeCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else if(pepsiCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else if(fantaCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else if(amalaCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else if(semoCheck.isSelected()){ 
            doneButton.setEnabled(true);
        } 
         else { 
          doneButton.setEnabled(false);
         }
    
  
        
           
         }   
   
    

   
         
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        minButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        receiptButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        receiptArea = new javax.swing.JTextArea();
        doneButton = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        riceLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        beansCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        riceCombo = new javax.swing.JComboBox();
        beansLabel = new javax.swing.JLabel();
        saladCheck = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        saladCombo = new javax.swing.JComboBox();
        plantainLabel = new javax.swing.JLabel();
        beansCheck = new javax.swing.JCheckBox();
        plantainCheck = new javax.swing.JCheckBox();
        plantainCombo = new javax.swing.JComboBox();
        saladLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        eggCheck = new javax.swing.JCheckBox();
        eggCombo = new javax.swing.JComboBox();
        eggLabel = new javax.swing.JLabel();
        fishCheck = new javax.swing.JCheckBox();
        meatCombo = new javax.swing.JComboBox();
        meatLabel = new javax.swing.JLabel();
        meatCheck = new javax.swing.JCheckBox();
        fishCombo = new javax.swing.JComboBox();
        fishLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        semoCombo = new javax.swing.JComboBox();
        semoLabel = new javax.swing.JLabel();
        semoCheck = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        amalaCheck = new javax.swing.JCheckBox();
        amalaCombo = new javax.swing.JComboBox();
        amalaLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pyamCheck = new javax.swing.JCheckBox();
        pyamCombo = new javax.swing.JComboBox();
        pyamLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        fantaCheck = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        cokeCheck = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        pepsiCheck = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        cokeCombo = new javax.swing.JComboBox();
        cokeLabel = new javax.swing.JLabel();
        fantaLabel = new javax.swing.JLabel();
        pepsiLabel = new javax.swing.JLabel();
        fantaCombo = new javax.swing.JComboBox();
        pepsiCombo = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        riceCheck = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        staff = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CafeteriaTickettingSystem");
        setIconImages(null);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 4));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/mnm.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/well.jpg"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hot.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        closeButton.setBackground(new java.awt.Color(255, 0, 51));
        closeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        minButton.setBackground(new java.awt.Color(0, 0, 153));
        minButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        minButton.setForeground(new java.awt.Color(255, 255, 255));
        minButton.setText("-");
        minButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));

        receiptButton.setBackground(new java.awt.Color(0, 102, 102));
        receiptButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        receiptButton.setForeground(new java.awt.Color(255, 255, 255));
        receiptButton.setText("RECEIPT");
        receiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptButtonActionPerformed(evt);
            }
        });

        printButton.setBackground(new java.awt.Color(0, 204, 102));
        printButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        printButton.setForeground(new java.awt.Color(255, 255, 255));
        printButton.setText("PRINT");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        confirmButton.setBackground(new java.awt.Color(0, 102, 0));
        confirmButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("CONFIRM");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(java.awt.Color.red);
        resetButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("RESET");
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        receiptArea.setEditable(false);
        receiptArea.setColumns(20);
        receiptArea.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        receiptArea.setForeground(new java.awt.Color(204, 0, 0));
        receiptArea.setRows(5);
        jScrollPane1.setViewportView(receiptArea);

        doneButton.setBackground(new java.awt.Color(0, 51, 204));
        doneButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        doneButton.setForeground(new java.awt.Color(255, 255, 255));
        doneButton.setText("DONE");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(204, 0, 0));
        logout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jLabel9.setText("SEARCH TICKET_ID");

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(receiptButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(printButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jButton2)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(logout)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        riceLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        riceLabel.setText("QUANTITY");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/images.jpg"))); // NOI18N

        beansCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("       FOOD ITEMS");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/rice.PNG"))); // NOI18N

        riceCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        beansLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        beansLabel.setText("QUANTITY");

        saladCheck.setBackground(new java.awt.Color(255, 255, 255));
        saladCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saladCheck.setText("SALAD");
        saladCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saladCheckMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/salad.JPG"))); // NOI18N

        saladCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        plantainLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        plantainLabel.setText("QUANTITY");

        beansCheck.setBackground(new java.awt.Color(255, 255, 255));
        beansCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        beansCheck.setText("BEANS");
        beansCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beansCheckMouseClicked(evt);
            }
        });
        beansCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beansCheckActionPerformed(evt);
            }
        });

        plantainCheck.setBackground(new java.awt.Color(255, 255, 255));
        plantainCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        plantainCheck.setText("PLANTAIN");
        plantainCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plantainCheckMouseClicked(evt);
            }
        });
        plantainCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantainCheckActionPerformed(evt);
            }
        });

        plantainCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        saladLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        saladLabel.setText("QUANTITY");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/plaintain.jpg"))); // NOI18N

        eggCheck.setBackground(new java.awt.Color(255, 255, 255));
        eggCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eggCheck.setText("EGG");
        eggCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eggCheckMouseClicked(evt);
            }
        });

        eggCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        eggLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        eggLabel.setText("QUANTITY");

        fishCheck.setBackground(new java.awt.Color(255, 255, 255));
        fishCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fishCheck.setText("FISH");
        fishCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fishCheckMouseClicked(evt);
            }
        });

        meatCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        meatCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatComboActionPerformed(evt);
            }
        });

        meatLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        meatLabel.setText("QUANTITY");

        meatCheck.setBackground(new java.awt.Color(255, 255, 255));
        meatCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        meatCheck.setText("MEAT");
        meatCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meatCheckMouseClicked(evt);
            }
        });

        fishCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        fishCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishComboActionPerformed(evt);
            }
        });

        fishLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        fishLabel.setText("QUANTITY");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/NN.jpg"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/PYAM.jpg"))); // NOI18N

        semoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        semoLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        semoLabel.setText("QUANTITY");

        semoCheck.setBackground(new java.awt.Color(255, 255, 255));
        semoCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        semoCheck.setText("SEMO");
        semoCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semoCheckMouseClicked(evt);
            }
        });
        semoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semoCheckActionPerformed(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/ii.jpg"))); // NOI18N

        amalaCheck.setBackground(new java.awt.Color(255, 255, 255));
        amalaCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        amalaCheck.setText("AMALA");
        amalaCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amalaCheckMouseClicked(evt);
            }
        });
        amalaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amalaCheckActionPerformed(evt);
            }
        });

        amalaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        amalaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amalaComboActionPerformed(evt);
            }
        });

        amalaLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        amalaLabel.setText("QUANTITY");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/combo.jpg"))); // NOI18N

        pyamCheck.setBackground(new java.awt.Color(255, 255, 255));
        pyamCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pyamCheck.setText("P.YAM");
        pyamCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pyamCheckMouseClicked(evt);
            }
        });

        pyamCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        pyamLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pyamLabel.setText("QUANTITY");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 4));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("DRINKS");

        fantaCheck.setBackground(new java.awt.Color(255, 255, 255));
        fantaCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fantaCheck.setText("FANTA");
        fantaCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fantaCheckMouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/coke.jpg"))); // NOI18N

        cokeCheck.setBackground(new java.awt.Color(255, 255, 255));
        cokeCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cokeCheck.setText("COKE");
        cokeCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cokeCheckMouseClicked(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/pepsi.jpg"))); // NOI18N

        pepsiCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pepsiCheck.setText("PEPSI");
        pepsiCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pepsiCheckMouseClicked(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/fanta.jpg"))); // NOI18N

        cokeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cokeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeComboActionPerformed(evt);
            }
        });

        cokeLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cokeLabel.setText("QUANTITY");

        fantaLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        fantaLabel.setText("QUANTITY");

        pepsiLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pepsiLabel.setText("QUANTITY");

        fantaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        fantaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaComboActionPerformed(evt);
            }
        });

        pepsiCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        pepsiCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsiComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel26))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cokeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cokeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fantaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fantaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(pepsiCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pepsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pepsiCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(fantaCheck))))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(cokeCheck)
                    .addContainerGap(236, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(jLabel30)
                    .addContainerGap(180, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(cokeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cokeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fantaCheck)
                    .addComponent(fantaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fantaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(pepsiCheck)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(pepsiLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pepsiCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(19, 19, 19))))))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(cokeCheck)
                    .addContainerGap(343, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(162, Short.MAX_VALUE)
                    .addComponent(jLabel30)
                    .addGap(146, 146, 146)))
        );

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/boiled egg.jpg"))); // NOI18N

        riceCheck.setBackground(new java.awt.Color(255, 255, 255));
        riceCheck.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        riceCheck.setText("RICE");
        riceCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riceCheckMouseClicked(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/o.jpg"))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("STAFF :");

        staff.setForeground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(riceCheck)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(beansCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eggCheck)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(plantainCheck)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(saladCheck)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(staff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(riceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(meatCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(meatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(pyamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(meatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pyamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(beansCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(fishCheck))
                            .addComponent(plantainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beansLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fishLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fishCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(plantainCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(pyamCheck))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(riceLabel)
                            .addComponent(eggLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(saladCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(amalaCheck))
                                    .addComponent(saladLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(eggCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(semoCheck)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(semoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(semoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(amalaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(amalaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(700, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(334, 334, 334)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(454, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(riceCheck)
                                        .addGap(68, 68, 68)
                                        .addComponent(beansCheck))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(staff, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(riceLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(meatCheck)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(riceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(beansLabel)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(beansCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fishCheck))
                                                .addGap(2, 2, 2)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(plantainCheck)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(plantainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(plantainCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pyamCheck))
                                .addGap(26, 26, 26))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(meatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(meatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fishLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fishCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(pyamLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pyamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saladCheck)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(saladLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(saladCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(amalaCheck)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(eggCheck)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(eggLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eggCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(semoCheck))
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(semoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(semoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(amalaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amalaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(391, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(354, Short.MAX_VALUE)))
        );

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here: 
        confirmButton.setEnabled(false);
        receiptButton.setEnabled(true);  
        receiptArea.setForeground(Color.black);
        receiptArea.setText(" \n\n\n " + "  THANKS FOR YOUR PATRONAGE" + "\n\n\n" + "   CLICK ON THE RECEIPT BUTTON " +"\n\n\n"+ "      FOR YOUR RECEIPT");
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void beansCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beansCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beansCheckActionPerformed

    private void plantainCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantainCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plantainCheckActionPerformed

    private void semoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semoCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semoCheckActionPerformed

    private void amalaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amalaCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amalaCheckActionPerformed

    private void fishComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fishComboActionPerformed

    private void meatComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meatComboActionPerformed

    private void amalaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amalaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amalaComboActionPerformed

    private void fantaCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fantaCheckMouseClicked
        // TODO add your handling code here:  
       if (fantaCheck.isSelected()){ 
        doneButton.setEnabled(true);
         fantaLabel.setVisible(true); 
         fantaCombo.setEnabled(true);
         doneButton.setEnabled(true);
        }else{ 
           
            fantaLabel.setVisible(false); 
         fantaCombo.setEnabled(false);  
         fantaCombo.setSelectedItem(Integer.toString(0)); 
        }  
        
    }//GEN-LAST:event_fantaCheckMouseClicked

    private void riceCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riceCheckMouseClicked
        // TODO add your handling code here: 
        if (riceCheck.isSelected()){ 
        doneButton.setEnabled(true);
         riceLabel.setVisible(true); 
         riceCombo.setEnabled(true); 
         doneButton.setEnabled(true);
        }else{ 
            
            riceLabel.setVisible(false); 
         riceCombo.setEnabled(false);  
         riceCombo.setSelectedItem(Integer.toString(0)); 
        }
    }//GEN-LAST:event_riceCheckMouseClicked

    private void cokeCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cokeCheckMouseClicked
        // TODO add your handling code here: 
       if (cokeCheck.isSelected()){ 
        doneButton.setEnabled(true);
         cokeLabel.setVisible(true); 
         cokeCombo.setEnabled(true);  
         doneButton.setEnabled(true);
        }else{ 
           
            cokeLabel.setVisible(false); 
         cokeCombo.setEnabled(false);  
         cokeCombo.setSelectedItem(Integer.toString(0)); 
        } 
    }//GEN-LAST:event_cokeCheckMouseClicked

    private void pepsiCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pepsiCheckMouseClicked
        // TODO add your handling code here: 
        if (pepsiCheck.isSelected()){ 
        doneButton.setEnabled(true);
         pepsiLabel.setVisible(true); 
         pepsiCombo.setEnabled(true); 
         doneButton.setEnabled(true);
        }else{ 
            
            pepsiLabel.setVisible(false); 
         pepsiCombo.setEnabled(false);  
         pepsiCombo.setSelectedItem(Integer.toString(0)); 
        } 
    }//GEN-LAST:event_pepsiCheckMouseClicked

    private void cokeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cokeComboActionPerformed

    private void fantaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fantaComboActionPerformed

    private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox13ActionPerformed

    private void pepsiComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsiComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pepsiComboActionPerformed

    private void beansCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beansCheckMouseClicked
        // TODO add your handling code here: 
        if (beansCheck.isSelected()){ 
        doneButton.setEnabled(true);
         beansLabel.setVisible(true); 
         beansCombo.setEnabled(true);
         doneButton.setEnabled(true);
        }else{ 
          
            beansLabel.setVisible(false); 
         beansCombo.setEnabled(false); 
         beansCombo.setSelectedItem(Integer.toString(0));
        }
    }//GEN-LAST:event_beansCheckMouseClicked

    private void plantainCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plantainCheckMouseClicked
        // TODO add your handling code here:  
        
        if (plantainCheck.isSelected()){ 
        doneButton.setEnabled(true);
         plantainLabel.setVisible(true); 
         plantainCombo.setEnabled(true);
         doneButton.setEnabled(true);
        }else{ 
            
           plantainLabel.setVisible(false); 
         plantainCombo.setEnabled(false); 
         plantainCombo.setSelectedItem(Integer.toString(0));
        }
    }//GEN-LAST:event_plantainCheckMouseClicked

    private void saladCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saladCheckMouseClicked
        // TODO add your handling code here: 
         if (saladCheck.isSelected()){ 
        doneButton.setEnabled(true);
         saladLabel.setVisible(true); 
         saladCombo.setEnabled(true); 
         doneButton.setEnabled(true);
        }else{ 
            
           saladLabel.setVisible(false); 
         saladCombo.setEnabled(false); 
         saladCombo.setSelectedItem(Integer.toString(0));
        }
    }//GEN-LAST:event_saladCheckMouseClicked

    private void eggCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eggCheckMouseClicked
        // TODO add your handling code here:
        if (eggCheck.isSelected()){ 
        doneButton.setEnabled(true);
         eggLabel.setVisible(true); 
         eggCombo.setEnabled(true); 
         doneButton.setEnabled(true);
        }else{ 
         
           eggLabel.setVisible(false); 
         eggCombo.setEnabled(false); 
         eggCombo.setSelectedItem(Integer.toString(0));
        }
    }//GEN-LAST:event_eggCheckMouseClicked

    private void meatCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meatCheckMouseClicked
        // TODO add your handling code here: 
         if (meatCheck.isSelected()){ 
        doneButton.setEnabled(true);
         meatLabel.setVisible(true); 
         meatCombo.setEnabled(true);  
         doneButton.setEnabled(true);
        }else{ 
             
          meatLabel.setVisible(false); 
         meatCombo.setEnabled(false); 
         meatCombo.setSelectedItem(Integer.toString(0));
        }
    }//GEN-LAST:event_meatCheckMouseClicked

    private void fishCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fishCheckMouseClicked
        // TODO add your handling code here: 
         if (fishCheck.isSelected()){ 
        doneButton.setEnabled(true);
         fishLabel.setVisible(true); 
         fishCombo.setEnabled(true); 
         doneButton.setEnabled(true);
        }else{ 
            
           fishLabel.setVisible(false); 
         fishCombo.setEnabled(false); 
         fishCombo.setSelectedItem(Integer.toString(0));
        }
    }//GEN-LAST:event_fishCheckMouseClicked

    private void pyamCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pyamCheckMouseClicked
        // TODO add your handling code here: 
          if (pyamCheck.isSelected()){ 
              doneButton.setEnabled(true);
         pyamLabel.setVisible(true); 
         pyamCombo.setEnabled(true);  
         doneButton.setEnabled(true);
        }else{ 
              
           pyamLabel.setVisible(false); 
         pyamCombo.setEnabled(false); 
         pyamCombo.setSelectedItem(Integer.toString(0));
        }
    }//GEN-LAST:event_pyamCheckMouseClicked

    private void amalaCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amalaCheckMouseClicked
        // TODO add your handling code here: 
          if (amalaCheck.isSelected()){ 
              doneButton.setEnabled(true);
         amalaLabel.setVisible(true); 
         amalaCombo.setEnabled(true);  
         doneButton.setEnabled(true);
        }else{ 
        
           amalaLabel.setVisible(false); 
         amalaCombo.setEnabled(false); 
         amalaCombo.setSelectedItem(Integer.toString(0));
        }
    }//GEN-LAST:event_amalaCheckMouseClicked

    private void semoCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semoCheckMouseClicked
        // TODO add your handling code here: 
         if (semoCheck.isSelected()){ 
             doneButton.setEnabled(true);
         semoLabel.setVisible(true); 
         semoCombo.setEnabled(true);  
         doneButton.setEnabled(true);
        }else{ 
     
           semoLabel.setVisible(false); 
         semoCombo.setEnabled(false); 
         semoCombo.setSelectedItem(Integer.toString(0));
        }
    }//GEN-LAST:event_semoCheckMouseClicked

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            // TODO add your handling code here:
            receiptArea.print();
        } catch (PrinterException ex) {
            Logger.getLogger(FinalTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:  
         printButton.setEnabled(false);
         riceLabel.setVisible(false); 
         riceCombo.setEnabled(false); 
         beansLabel.setVisible(false); 
         beansCombo.setEnabled(false); 
         plantainLabel.setVisible(false); 
         plantainCombo.setEnabled(false); 
         saladLabel.setVisible(false); 
         saladCombo.setEnabled(false); 
         eggLabel.setVisible(false); 
         eggCombo.setEnabled(false); 
         meatLabel.setVisible(false); 
         meatCombo.setEnabled(false); 
         fishLabel.setVisible(false); 
         fishCombo.setEnabled(false); 
         pyamLabel.setVisible(false); 
         pyamCombo.setEnabled(false);
         semoLabel.setVisible(false); 
         semoCombo.setEnabled(false); 
         cokeLabel.setVisible(false); 
         cokeCombo.setEnabled(false); 
         fantaLabel.setVisible(false); 
         fantaCombo.setEnabled(false);
         pepsiLabel.setVisible(false); 
         pepsiCombo.setEnabled(false); 
         amalaLabel.setVisible(false); 
         amalaCombo.setEnabled(false);  
         confirmButton.setEnabled(false);
         receiptButton.setEnabled(false); 
         doneButton.setEnabled(false);  
         riceCheck.setSelected(false); 
         beansCheck.setSelected(false); 
         plantainCheck.setSelected(false); 
         semoCheck.setSelected(false); 
         amalaCheck.setSelected(false); 
         eggCheck.setSelected(false); 
         saladCheck.setSelected(false); 
         pyamCheck.setSelected(false); 
         fishCheck.setSelected(false); 
         meatCheck.setSelected(false);
         cokeCheck.setSelected(false); 
         pepsiCheck.setSelected(false); 
         fantaCheck.setSelected(false); 
         receiptArea.setForeground(Color.red); 
          riceCombo.setSelectedItem(Integer.toString(0)); 
          beansCombo.setSelectedItem(Integer.toString(0)); 
          plantainCombo.setSelectedItem(Integer.toString(0)); 
          saladCombo.setSelectedItem(Integer.toString(0)); 
          fishCombo.setSelectedItem(Integer.toString(0)); 
          pyamCombo.setSelectedItem(Integer.toString(0)); 
          cokeCombo.setSelectedItem(Integer.toString(0)); 
          fantaCombo.setSelectedItem(Integer.toString(0)); 
          pepsiCombo.setSelectedItem(Integer.toString(0)); 
          meatCombo.setSelectedItem(Integer.toString(0)); 
          amalaCombo.setSelectedItem(Integer.toString(0)); 
          semoCombo.setSelectedItem(Integer.toString(0)); 
          eggCombo.setSelectedItem(Integer.toString(0)); 
        receiptArea.setText( "           WELCOME" + "\n\n" + "    PLEASE CLICK ON THE" + "\n\n\n"  +  "         DONE BUTTON     " + "\n\n\n\n" + "   AFTER MAKING YOUR ORDER  "); 
    }//GEN-LAST:event_resetButtonActionPerformed

    private void receiptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptButtonActionPerformed
        // TODO add your handling code here:   
        receiptButton.setEnabled(false);
        printButton.setEnabled(true);
        int Total[] = new int[15];  
        int  qty = 0 ; 
        int  sum = 0 ; 
        int  total = 0 ; 
        int  bill = 0 ;
         String type;  
         Calendar  cal = new GregorianCalendar(); 
         int d,m,y,h,min,se; 
         d = cal.get(Calendar.DAY_OF_MONTH); 
         m = cal.get(Calendar.MONTH); 
         y = cal.get(Calendar.YEAR); 
         
         h = cal.get(Calendar.HOUR); 
         min = cal.get(Calendar.MINUTE); 
         se = cal.get(Calendar.SECOND);  
         
           
          // for pm or am 
         String s  = "a";
         Date  da = new Date();
         SimpleDateFormat sdf = new SimpleDateFormat(s);  
         String user = staff.getText();
       
        
         
         receiptArea.setText("*********** RECEIPT **********" + "\n"   
                             +"        LIZMO'S CAFETERIA " + "\n"
                             +"TIME :" + h + ":" + min + " " + sdf.format(da) + "\n"
                             +"DATE :" + d +"/" + (m+1) + "/" + y + "\n" 
                             +"SOLD BY :" + user +  "\n"
                             +"ITEMS        QTY      PRICE(NGN)" + "\n" 
                             +"-------------------------------"); 
         
        if(riceCheck.isSelected()){   
            
        type = (String)riceCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
        Total[0] = 50 * qty; 
        receiptArea.setText(receiptArea.getText() + "\n" 
                            +"RICE" + "          "+     "X"+ qty   + "          " +  Total[0]);
      
        }  
         if (beansCheck.isSelected()){  
             doneButton.setEnabled(true);
        type = (String)beansCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
       Total[1] = 50 * qty; 
        receiptArea.setText(receiptArea.getText() + "\n" 
                            +"BEANS" + "         "+     "X"+ qty   + "          " +  Total[1]);
      
       
        }
         if (cokeCheck.isSelected()){ 
           
        type = (String)cokeCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
       Total[2] = 100 * qty; 
        receiptArea.setText(receiptArea.getText() + "\n" 
                            +"COKE" + "          "+     "X"+ qty   + "          " +  Total[2]);
      
        }  
        if (fantaCheck.isSelected()){ 
            
        type = (String)fantaCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
       Total[3] = 100 * qty;
        receiptArea.setText(receiptArea.getText() + "\n" 
                            +"FANTA" + "         "+     "X"+ qty   + "          " +  Total[3]);
      
        
        } 
        if (pepsiCheck.isSelected()){ 
            
        type = (String)pepsiCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
        Total[4] = 100 * qty; 
         receiptArea.setText(receiptArea.getText() + "\n" 
                            +"PEPSI" + "         "+     "X"+ qty   + "          " +  Total[4]);
      
        
        }
        if (amalaCheck.isSelected()){ 
            
        type = (String)amalaCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
        Total[5] = 50 * qty; 
          receiptArea.setText(receiptArea.getText() + "\n" 
                            +"AMALA" + "         "+     "X"+ qty   + "          " +  Total[5]);
        
        } 
         if (semoCheck.isSelected()){ 
      
        type = (String)semoCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
        Total[6] = 50 * qty;  
         receiptArea.setText(receiptArea.getText() + "\n" 
                            +"SEMO" + "          "+     "X"+ qty   + "          " +  Total[6]);
        
      
        } 
         if (meatCheck.isSelected()){ 
         
        type = (String)meatCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
       Total[7]= 50 * qty; 
        receiptArea.setText(receiptArea.getText() + "\n" 
                            +"MEAT" + "          "+     "X"+ qty   + "          " +  Total[7]);
       
        } 
         if (fishCheck.isSelected()){ 
        
        type = (String)fishCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
       Total[8] = 50 * qty; 
        receiptArea.setText(receiptArea.getText() + "\n" 
                            +"FISH" + "          "+     "X"+ qty   + "          " +  Total[8]);
        
        } 
         if (plantainCheck.isSelected()){ 
           
        type = (String)plantainCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
        Total[9]= 10 * qty; 
         receiptArea.setText(receiptArea.getText() + "\n" 
                            +"PLANTAIN" + "      "+     "X"+ qty   + "          " +  Total[9]);
        
        }
         if (pyamCheck.isSelected()){ 
           
        type = (String)pyamCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
        Total[10] = 50 * qty; 
        receiptArea.setText(receiptArea.getText() + "\n" 
                            +"P.YAM" + "         "+     "X"+ qty   + "          " +  Total[10]);
        
        }
         if (saladCheck.isSelected()){ 
             
        type = (String)saladCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
       Total[11] = 50 * qty; 
       receiptArea.setText(receiptArea.getText() + "\n" 
                            +"SALAD" + "         "+     "X"+ qty   + "          " +  Total[11]);
        
        }
         if (eggCheck.isSelected()){ 
             
        type = (String)eggCombo.getSelectedItem(); 
        qty = Integer.parseInt(type);  
        Total[12] = 50 * qty; 
         receiptArea.setText(receiptArea.getText() + "\n" 
                            +"EGG" + "           "+     "X"+ qty   + "          " +  Total[12]);
        
         } 
        for (int c = 0 ; c<14; c++){
         bill = bill + Total[c];  
         System.out.println(Total[c]);
        
        } 
        receiptArea.setText(receiptArea.getText() + "\n" 
        +"-------------------------------"+"\n" 
        +"TOTAL     :" + bill + "(NGN)" + "\n" 
        +"TICKET ID :" + d + (m+1) + y + h + min + se  + "\n"        
        +"-------------------------------"+"\n" 
        +"-------------------------------"        
        );    
        
        
        
        try{
            String query = "insert into sales values(?,?,?,?,?,?)";
            pst = conn.prepareStatement(query);
            pst.setString(1,"" + d + (m+1) + y + h + min + se); // TICKET ID
            pst.setString(2,user); // SOLD BY
            pst.setString(3,  h + ":" + min + " " + sdf.format(da)); // TIME
            pst.setString(4, d +"/" + (m+1) + "/" + y); // DATE
            pst.setString(5,receiptArea.getText()); // RECEIPT
            pst.setInt(6,bill); // BILL
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"ORDER HAS BEEN SENT TO THE DATABASE");
            
        }catch(Exception e){ 
            JOptionPane.showMessageDialog(null, "ERROR!!! DATA IS NOT COMPLETE");
        
        
        }
 
         
    }//GEN-LAST:event_receiptButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here: 
        doneButton.setEnabled(false); 
        confirmButton.setEnabled(true);   
        receiptArea.setForeground(Color.black);
        receiptArea.setText(" PLEASE CROSS-CHECK YOUR ORDER" + "\n\n\n" + "        IF YOU WISH TO" + "\n\n\n" + " MAKE CHANGE WHERE NECCESSARY " + "\n\n\n" + "     CLICK ON CONFIRM BUTTON" +"\n\n" + "           TO PROCEED... ");
    }//GEN-LAST:event_doneButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:  
        
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void minButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minButtonActionPerformed
        // TODO add your handling code here: 
        this.setState(FinalTicket.ICONIFIED);
    }//GEN-LAST:event_minButtonActionPerformed

    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButtonMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here: 
        JOptionPane.showMessageDialog(null,"GOOD BYE " + staff.getText());
        new cafeLogIn(null).setVisible(true); 
        this.hide();
    }//GEN-LAST:event_logoutActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:  
         try{
            String query = "select * from SALES where TicketID =?";
            pst = conn.prepareStatement(query);
            pst.setString(1,ID.getText());
            rs = pst.executeQuery();
            
            
            
            if(rs.next()){
              String add1 = rs.getString("RECEIPT"); 
              JOptionPane.showMessageDialog(null,"TICKET FOUND !!!");
              receiptArea.setText(add1); 
            }else { 
            JOptionPane.showMessageDialog(null, "TICKET NOT FOUND!!!");
            }
            
           
            
        }
         catch(Exception e){ 
          
        
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String [] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {  
                
               
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JCheckBox amalaCheck;
    private javax.swing.JComboBox amalaCombo;
    private javax.swing.JLabel amalaLabel;
    private javax.swing.JCheckBox beansCheck;
    private javax.swing.JComboBox beansCombo;
    private javax.swing.JLabel beansLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JCheckBox cokeCheck;
    private javax.swing.JComboBox cokeCombo;
    private javax.swing.JLabel cokeLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JCheckBox eggCheck;
    private javax.swing.JComboBox eggCombo;
    private javax.swing.JLabel eggLabel;
    private javax.swing.JCheckBox fantaCheck;
    private javax.swing.JComboBox fantaCombo;
    private javax.swing.JLabel fantaLabel;
    private javax.swing.JCheckBox fishCheck;
    private javax.swing.JComboBox fishCombo;
    private javax.swing.JLabel fishLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JCheckBox meatCheck;
    private javax.swing.JComboBox meatCombo;
    private javax.swing.JLabel meatLabel;
    private javax.swing.JButton minButton;
    private javax.swing.JCheckBox pepsiCheck;
    private javax.swing.JComboBox pepsiCombo;
    private javax.swing.JLabel pepsiLabel;
    private javax.swing.JCheckBox plantainCheck;
    private javax.swing.JComboBox plantainCombo;
    private javax.swing.JLabel plantainLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JCheckBox pyamCheck;
    private javax.swing.JComboBox pyamCombo;
    private javax.swing.JLabel pyamLabel;
    private javax.swing.JTextArea receiptArea;
    private javax.swing.JButton receiptButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JCheckBox riceCheck;
    private javax.swing.JComboBox riceCombo;
    private javax.swing.JLabel riceLabel;
    private javax.swing.JCheckBox saladCheck;
    private javax.swing.JComboBox saladCombo;
    private javax.swing.JLabel saladLabel;
    private javax.swing.JCheckBox semoCheck;
    private javax.swing.JComboBox semoCombo;
    private javax.swing.JLabel semoLabel;
    private javax.swing.JLabel staff;
    // End of variables declaration//GEN-END:variables
}
