package RandoBet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADEBAYO ADEMOLA
 */
import javax.swing.*; 
import java.util.Random;
public class rando extends javax.swing.JFrame {

    /**
     * Creates new form rando
     */
    public rando() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        SH = new javax.swing.JCheckBox();
        RN = new javax.swing.JCheckBox();
        onedir = new javax.swing.JCheckBox();
        twodir = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        threedir = new javax.swing.JCheckBox();
        fourdir = new javax.swing.JCheckBox();
        fivedir = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        num1 = new javax.swing.JTextField();
        res1 = new javax.swing.JTextField();
        res3 = new javax.swing.JTextField();
        res4 = new javax.swing.JTextField();
        res5 = new javax.swing.JTextField();
        num5 = new javax.swing.JTextField();
        num4 = new javax.swing.JTextField();
        num3 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        res2 = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        play = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));

        jPanel7.setBackground(new java.awt.Color(0, 204, 0));
        jPanel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        SH.setBackground(new java.awt.Color(51, 204, 0));
        SH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SH.setText("SAME_HOLE ");

        RN.setBackground(new java.awt.Color(51, 204, 0));
        RN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RN.setText("RANDOM");

        onedir.setBackground(new java.awt.Color(51, 204, 0));
        onedir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        onedir.setText("1 - DIRECT");

        twodir.setBackground(new java.awt.Color(51, 204, 0));
        twodir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        twodir.setText("2 - DIRECT");

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("ODDS:");

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setText("G-Type");

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setText("GAME:");

        threedir.setBackground(new java.awt.Color(51, 204, 0));
        threedir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        threedir.setText("3 - DIRECT");

        fourdir.setBackground(new java.awt.Color(51, 204, 0));
        fourdir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fourdir.setText("4 - DIRECT");

        fivedir.setBackground(new java.awt.Color(51, 204, 0));
        fivedir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fivedir.setText("5- DIRECT");

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("4.54");

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("3.23");

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("11.65");

        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jTextField7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("8.25");

        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("20.65");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel8)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(onedir)
                            .addComponent(SH, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(twodir)
                        .addGap(59, 59, 59)
                        .addComponent(threedir)
                        .addGap(65, 65, 65)
                        .addComponent(fourdir)
                        .addGap(66, 66, 66)
                        .addComponent(fivedir))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onedir)
                    .addComponent(threedir)
                    .addComponent(twodir)
                    .addComponent(fourdir)
                    .addComponent(fivedir))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        reset.setBackground(new java.awt.Color(204, 0, 0));
        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(51, 51, 255));

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));

        jLabel16.setBackground(new java.awt.Color(153, 153, 153));
        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel16.setText("PLAYER:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel15.setText("RESULT:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        res1.setEditable(false);

        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(res1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(res2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(res3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(res4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(res5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(168, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 62, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(fn)
                                .addContainerGap())))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(1, 1, 1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(res1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(res2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(res3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(res4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(res5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("HOW TO PLAY:\n1. Select the type of game type you want\n2. Pick your RANDO\n3. Stake the amount you want, but remember the higher your stakings the higher your return winnings\n4. The result will display immediately our client spin the vault\n5. GOODLUCK");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setText("STAKE:");

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setText("WINNINGS:");

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setText("BONUS:");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("PRINT RECIPT");

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel11.setText("J A C K P O T    W I N N E R");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel13.setText("ID NUMBER:");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        play.setBackground(new java.awt.Color(0, 102, 0));
        play.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        play.setForeground(new java.awt.Color(255, 255, 255));
        play.setText("PLAY");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        num1.setText(null);
        num2.setText(null);
        num3.setText(null);
        num4.setText(null);
        num5.setText(null);

        res1.setText(null);

        res2.setText(null);

        res3.setText(null);

        res4.setText(null);

        res5.setText(null);

        SH.setSelected(false);
        RN.setSelected(false);
        onedir.setSelected(false);
        twodir.setSelected(false);
        play.setEnabled(true);

    }//GEN-LAST:event_resetActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:

        Random r = new Random();
        int n1 = Integer.parseInt(num1.getText());
        int n2 = Integer.parseInt(num2.getText());
        int n3 = Integer.parseInt(num3.getText());
        int n4 = Integer.parseInt(num4.getText());
        int n5 = Integer.parseInt(num5.getText());

        int r1 = r.nextInt(45) + 1;
        res1.setText(String.valueOf(r1));

        int r2 = r.nextInt(45) + 1;
        res2.setText(String.valueOf(r2));

        int r3 = r.nextInt(45) + 1;
        res3.setText(String.valueOf(r3));

        int r4 = r.nextInt(45) + 1;
        res4.setText(String.valueOf(r4));

        int r5 = r.nextInt(45) + 1;
        res5.setText(String.valueOf(r5));

        if (r1 == r2 || r1 == r3 || r1 == r4 || r1 ==  r5) {
            r1 = r1 + 1;
            res1.setText(String.valueOf(r1));
        }
        if (r2 == r1 || r2 == r3 || r2 == r4 || r2 == r5) {
            r2 = r2 + 2;
            res2.setText(String.valueOf(r2));
        }
        if (r3 == r1 || r3 == r2|| r3 == r4 || r1 ==  r5) {
            r3 = r3 + 3;
            res3.setText(String.valueOf(r3));
        }
        if (r4 == r1 || r4 == r2|| r4== r3 || r4 ==  r5) {
            r4 = r4 + 4;
            res4.setText(String.valueOf(r4));
        }
        if (r5 == r1 || r5 == r2|| r5 == r4 || r5 ==  r3) {
            r5 = r5 + 5;
            res5.setText(String.valueOf(r5));
        } 
        
        
       
       

        //SAME HOLE ONE DIRECT
        if(SH.isSelected() && onedir.isSelected()){

            if (n1 == r1 || n2 == r2 || n3 == r3 || n4 == r4 || n5 == r5){
                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");

            }
            else {
                JOptionPane.showMessageDialog(null,"BET LOST!!!");

            } // SAME HOLE ONE DIRECT ENDED
        }

        //RANDOM ONE DIRECCT
        if(RN.isSelected() && onedir.isSelected()){

            if (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5){
                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");

            }

            else if (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5){
                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");

            }

            else if (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5){
                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");

            }

            else if (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5){
                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");

            }

            else  if (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5){

                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");

            }
            else {
                JOptionPane.showMessageDialog(null,"BET LOST!!!");

            }

        } // END OF RANDOM ONE DIRECT
       

        // RANDOM TWO DIRECT
        if(RN.isSelected() && twodir.isSelected()){

        }

        play.setEnabled(false); 
        
        // SAME HOLE 2 DIRECT

        if (SH.isSelected() && twodir.isSelected()) {
            if( n1 == r1  &&  n2 == r2 ) {

                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");

            }
            else if (n1 == r1  &&  n3 == r3){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }    
             
        
            else if (n1 == r1  &&  n4 == r4){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            
            }
            
             else if (n1 == r1  &&  n5 == r5){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }  
            
            
           
             else if (n2 == r2  &&  n3 == r3){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }   
             
             
             
               else if (n2 == r2  &&  n4 == r4){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }  
            
             
               else if (n2 == r2  &&  n5 == r5){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }  
             
               else if (n3 == r3  &&  n4 == r4){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }   
               
                 else if (n3 == r3  &&  n5 == r5){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }   
                 
                 
                 
                else if (n4 == r4  &&  n5 == r5){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }     
             
             
            else{
                JOptionPane.showMessageDialog(null,"BET LOST!!!");
            }

        } // END OF SAME HOLE TWO DIRECT   
        
        
        
        
        
         // SAMEHOLE 3 DIRECT
      
        if (SH.isSelected() && threedir.isSelected()) {
            if( n1 == r1  &&  n2 == r2 && n3 == r3) {

                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");

            }
            else if (n1 == r1  &&  n2 == r2 &&  n4 == r4){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }   
            
            
             else if (n1 == r1  &&  n2 == r2 &&  n5 == r5){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }  
            
            
           
             else if (n1 == r1  &&  n3 == r3 &&  n4 == r4){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }   
             
             
             
               else if (n1 == r1  &&  n3 == r3 &&  n5 == r5){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }  
            
             
               else if (n1 == r1  &&  n4 == r4 &&  n5 == r5){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }  
             
               else if (n2 == r2  &&  n3 == r3 &&  n4 == r4){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }   
               
                 else if (n2 == r2  &&  n3 == r3 &&  n5 == r5){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }   
                 
                 
                 
                else if (n2 == r2  &&  n4 == r4 &&  n5 == r5){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }     
                
                   else if (n3 == r3  &&  n4 == r4 &&  n5 == r5){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            } 
             
             
            else{
                JOptionPane.showMessageDialog(null,"BET LOST!!!");
            }

        } // END OF SAMEHOLE 3 DIRECT   
        
        
        
      //SAMEHOLE 4 DIRECT
      
        if (SH.isSelected() && fourdir.isSelected()) {
            if( n1 == r1  &&  n2 == r2 && n3 == r3  &&  n4 == r4) {

                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");

            }
            else if (n1 == r1  &&  n2 == r2 &&  n3 == r3 &&  n5 == r5){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }   
            
            
             else if (n1 == r1  &&  n2 == r2  &&  n4 == r4 &&  n5 == r5) { 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }  
            
            
           
             else if (n5 == r5 &&  n2 == r2 && n3 == r3  &&  n4 == r4) { 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }   
             
             
             
               else if (n1 == r1  &&  n3 == r3 &&  n5 == r5 &&  n4 == r4){ 
             JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            
            }  
            
             
  
             
            else{
                JOptionPane.showMessageDialog(null,"BET LOST!!!");
            }

        } // END OF SAMEHOLE 4 DIRECT   
        
           
        
        
        
           if (SH.isSelected() && fivedir.isSelected()) {
            if( n1 == r1  &&  n2 == r2 && n3 == r3  &&  n4 == r4 &&  n5 == r5) {

                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");

            }
             
  
             
            else{
                JOptionPane.showMessageDialog(null,"BET LOST!!!");
            }

        } // END OF SAMEHOLE 5 DIRECT   
        
        
           //RANDOM AND FIVE DIRECT 
           
         if (RN.isSelected() && fivedir.isSelected()){ 
               if ((n1 == r1 || n1 == r2 || n1 == r3 ||n1 == r4 || n1 == r5) && (n2 == r1 || n2 == r2 || n2 == r3 ||n2 == r4 || n2 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 ||n3 == r4 || n3 == r5) && (n4 == r1 || n4 == r2 || n4 == r3 ||n4 == r4 || n4 == r5) && (n5 == r1 || n5 == r2 || n5 == r3 ||n5 == r4 || n5 == r5)) { 
               
                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
               
               
               }
                 
            else{
                JOptionPane.showMessageDialog(null,"BET LOST!!!");
            } 
         }
               
               
       // RANDOM AND TWO DIRECT 
               
      if (RN.isSelected() && twodir.isSelected()){ 
         if ((n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5)){
          
                JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
         
         }
         else if ( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) ){ 
         
         JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
         }
        else if ( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5) ){ 
         
         JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
         }
        else if ( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5) ){ 
         
         JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
         }
      
          else if ( (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r3 || n3 == r5) ){ 
         
         JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
         }
        else if ( (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) && (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5) ){ 
         
         JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
         }
      
       else if ( (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) && (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5) ){ 
         
         JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
         }
        else if ( (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) && (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5) ){ 
         
         JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
         }
      
       else if ( (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) && (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5) ){ 
         
         JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
         }
      
      
       else if ( (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5) && (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5) ){ 
         
         JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
         }
      
         else{
                JOptionPane.showMessageDialog(null,"BET LOST!!!");
            }
      
      
      }       
        
        
      
        // RANDOM AND THREE DIRECT 
               
      if (RN.isSelected() && threedir.isSelected()){ 
      
          if( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5)){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
          }
      
           else if( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) &&  (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5)){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
           }
          
          
           else if( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) &&  (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5)){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
           }
     
           
           else if( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) &&  (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5)){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
           }
      
          
           else if( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) &&  (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5)){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
           }
            else if( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5) &&  (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5)){ 
           JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
            }     
      
          
           else if( (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) && (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5) &&  (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5)){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
           }
      
           else if( (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) &&  (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5)){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
           }
      
        else if( (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) &&  (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5)){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
        }
      
       else if( (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) && (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5) &&  (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5)){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
       } 
          
           else{
                JOptionPane.showMessageDialog(null,"BET LOST!!!");
            }
      }
      
      
       if (RN.isSelected() && fourdir.isSelected()){ 
      
          if ((n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) && (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5)){ 
           JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
          }          
          else if( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) && (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5) ){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
          
          }

         else if( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) && (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5) && (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5) ){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
          
          }
       else if( (n1 == r1 || n1 == r2 || n1 == r3 || n1 == r4 || n1 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) && (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5) && (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5) ){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
          
          }
       
       else if( (n2 == r1 || n2 == r2 || n2 == r3 || n2 == r4 || n2 == r5) && (n3 == r1 || n3 == r2 || n3 == r3 || n3 == r4 || n3 == r5) && (n4 == r1 || n4 == r2 || n4 == r3 || n4 == r4 || n4 == r5) && (n5 == r1 || n5 == r2 || n5 == r3 || n5 == r4 || n5 == r5) ){ 
          JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON THE BET!!!");
          
          }
       
        else{
                JOptionPane.showMessageDialog(null,"BET LOST!!!");
            }
       
       
       }
    }//GEN-LAST:event_playActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:  
    
        int d = Integer.parseInt(fn.getText());  
        fn.setText("CONVERTED " + d); 
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox RN;
    private javax.swing.JCheckBox SH;
    private javax.swing.JCheckBox fivedir;
    private javax.swing.JTextField fn;
    private javax.swing.JCheckBox fourdir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField num3;
    private javax.swing.JTextField num4;
    private javax.swing.JTextField num5;
    private javax.swing.JCheckBox onedir;
    private javax.swing.JButton play;
    private javax.swing.JTextField res1;
    private javax.swing.JTextField res2;
    private javax.swing.JTextField res3;
    private javax.swing.JTextField res4;
    private javax.swing.JTextField res5;
    private javax.swing.JButton reset;
    private javax.swing.JCheckBox threedir;
    private javax.swing.JCheckBox twodir;
    // End of variables declaration//GEN-END:variables
}
